

#ifndef _XMLPARSER_
#define _XMLPARSER_

#include "Model.h"
#include <vector>
#include <iostream>
#include <fstream>
#include <sstream>
#include <regex> //regular expression
#include "string.h"

// Used to parse the xml files generated by scorpio
class XMLParser {

public:
	XMLParser() {};
	~XMLParser() {};


	// parse a file and write the output in the vectors
	bool parse( int filename, GVersion &version);


};

#endif
